//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialDataGrabber.CVM.CVMWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cvm.gov.br/webservices/", ConfigurationName="CVMWeb.WsDownloadInfsSoap")]
    public interface WsDownloadInfsSoap {
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse retornaListaComptcDocs(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsParticRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse retornaListaComptcDocsPartic(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsAdmRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse retornaListaComptcDocsAdm(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadCadastroRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse solicAutorizDownloadCadastro(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqComptcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse solicAutorizDownloadArqComptc(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqEntregaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse solicAutorizDownloadArqEntrega(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqEntregaPorDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse solicAutorizDownloadArqEntregaPorData(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqAnualRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse solicAutorizDownloadArqAnual(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest request);
        
        // CODEGEN: Generating message contract since message retornaDtLmtEntrDocsArqsDispRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse retornaDtLmtEntrDocsArqsDisp(FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaDownloadDocsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse retornaListaDownloadDocs(FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest request);
        
        // CODEGEN: Generating message contract since message LoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinancialDataGrabber.CVM.CVMWeb.LoginResponse Login(FinancialDataGrabber.CVM.CVMWeb.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.LoginResponse> LoginAsync(FinancialDataGrabber.CVM.CVMWeb.LoginRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
    public partial class sessaoIdHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private int idSessaoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdSessao {
            get {
                return this.idSessaoField;
            }
            set {
                this.idSessaoField = value;
                this.RaisePropertyChanged("IdSessao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        public retornaListaComptcDocsRequest() {
        }
        
        public retornaListaComptcDocsRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsResult;
        
        public retornaListaComptcDocsResponse() {
        }
        
        public retornaListaComptcDocsResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsResult = retornaListaComptcDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsPartic", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsParticRequest() {
        }
        
        public retornaListaComptcDocsParticRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsParticResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsParticResult;
        
        public retornaListaComptcDocsParticResponse() {
        }
        
        public retornaListaComptcDocsParticResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsParticResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsParticResult = retornaListaComptcDocsParticResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdm", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsAdmRequest() {
        }
        
        public retornaListaComptcDocsAdmRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdmResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsAdmResult;
        
        public retornaListaComptcDocsAdmResponse() {
        }
        
        public retornaListaComptcDocsAdmResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsAdmResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsAdmResult = retornaListaComptcDocsAdmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastro", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string strDtRefer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadCadastroRequest() {
        }
        
        public solicAutorizDownloadCadastroRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.strDtRefer = strDtRefer;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastroResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadCadastroResult;
        
        public solicAutorizDownloadCadastroResponse() {
        }
        
        public solicAutorizDownloadCadastroResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadCadastroResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadCadastroResult = solicAutorizDownloadCadastroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptc", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtComptcDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqComptcRequest() {
        }
        
        public solicAutorizDownloadArqComptcRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtComptcDoc = strDtComptcDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptcResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqComptcResult;
        
        public solicAutorizDownloadArqComptcResponse() {
        }
        
        public solicAutorizDownloadArqComptcResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqComptcResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqComptcResult = solicAutorizDownloadArqComptcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntrega", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaRequest() {
        }
        
        public solicAutorizDownloadArqEntregaRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaResult;
        
        public solicAutorizDownloadArqEntregaResponse() {
        }
        
        public solicAutorizDownloadArqEntregaResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaResult = solicAutorizDownloadArqEntregaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorData", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtEntregaDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaPorDataRequest() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtEntregaDoc = strDtEntregaDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorDataResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaPorDataResult;
        
        public solicAutorizDownloadArqEntregaPorDataResponse() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaPorDataResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaPorDataResult = solicAutorizDownloadArqEntregaPorDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnual", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqAnualRequest() {
        }
        
        public solicAutorizDownloadArqAnualRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnualResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqAnualResult;
        
        public solicAutorizDownloadArqAnualResponse() {
        }
        
        public solicAutorizDownloadArqAnualResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqAnualResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqAnualResult = solicAutorizDownloadArqAnualResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDisp", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        public retornaDtLmtEntrDocsArqsDispRequest() {
        }
        
        public retornaDtLmtEntrDocsArqsDispRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDispResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string retornaDtLmtEntrDocsArqsDispResult;
        
        public retornaDtLmtEntrDocsArqsDispResponse() {
        }
        
        public retornaDtLmtEntrDocsArqsDispResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string retornaDtLmtEntrDocsArqsDispResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaDtLmtEntrDocsArqsDispResult = retornaDtLmtEntrDocsArqsDispResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpPartic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strNrPfPj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=3)]
        public string strDtIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=4)]
        public string strDtFim;
        
        public retornaListaDownloadDocsRequest() {
        }
        
        public retornaListaDownloadDocsRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpPartic = iCdTpPartic;
            this.strNrPfPj = strNrPfPj;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIni = strDtIni;
            this.strDtFim = strDtFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaDownloadDocsResult;
        
        public retornaListaDownloadDocsResponse() {
        }
        
        public retornaListaDownloadDocsResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string[] retornaListaDownloadDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaDownloadDocsResult = retornaListaDownloadDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iNrSist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strSenha;
        
        public LoginRequest() {
        }
        
        public LoginRequest(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iNrSist = iNrSist;
            this.strSenha = strSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader;
        
        public LoginResponse() {
        }
        
        public LoginResponse(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader) {
            this.sessaoIdHeader = sessaoIdHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsDownloadInfsSoapChannel : FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsDownloadInfsSoapClient : System.ServiceModel.ClientBase<FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap>, FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap {
        
        public WsDownloadInfsSoapClient() {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocs(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocs(request);
        }
        
        public string[] retornaListaComptcDocs(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocsAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocsPartic(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsPartic(request);
        }
        
        public string[] retornaListaComptcDocsPartic(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocsPartic(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsParticResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocsParticAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsParticAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocsParticAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocsAdm(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdm(request);
        }
        
        public string[] retornaListaComptcDocsAdm(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdm(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsAdmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaComptcDocsAdmAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdmAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadCadastro(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastro(request);
        }
        
        public string solicAutorizDownloadCadastro(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastro(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadCadastroAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqComptc(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptc(request);
        }
        
        public string solicAutorizDownloadArqComptc(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptc(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqComptcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqComptcAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptcAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqEntrega(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntrega(request);
        }
        
        public string solicAutorizDownloadArqEntrega(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntrega(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorData(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorData(request);
        }
        
        public string solicAutorizDownloadArqEntregaPorData(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorData(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaPorDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorDataAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqAnual(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnual(request);
        }
        
        public string solicAutorizDownloadArqAnual(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnual(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqAnualResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.solicAutorizDownloadArqAnualAsync(FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnualAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDisp(FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDisp(request);
        }
        
        public string retornaDtLmtEntrDocsArqsDisp(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDisp(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaDtLmtEntrDocsArqsDispResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDispAsync(FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDispAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDispAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaDownloadDocs(FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocs(request);
        }
        
        public string[] retornaListaDownloadDocs(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaDownloadDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaDownloadDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.retornaListaDownloadDocsAsync(FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).retornaListaDownloadDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancialDataGrabber.CVM.CVMWeb.LoginResponse FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.Login(FinancialDataGrabber.CVM.CVMWeb.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public void Login(ref FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            FinancialDataGrabber.CVM.CVMWeb.LoginRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            FinancialDataGrabber.CVM.CVMWeb.LoginResponse retVal = ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).Login(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.LoginResponse> FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap.LoginAsync(FinancialDataGrabber.CVM.CVMWeb.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancialDataGrabber.CVM.CVMWeb.LoginResponse> LoginAsync(FinancialDataGrabber.CVM.CVMWeb.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            FinancialDataGrabber.CVM.CVMWeb.LoginRequest inValue = new FinancialDataGrabber.CVM.CVMWeb.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            return ((FinancialDataGrabber.CVM.CVMWeb.WsDownloadInfsSoap)(this)).LoginAsync(inValue);
        }
    }
}
