//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVMDownload.CVMWebCotas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cvm.gov.br/webservices/", ConfigurationName="CVMWebCotas.WsDownloadInfsSoap")]
    public interface WsDownloadInfsSoap {
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse retornaListaComptcDocs(CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsParticRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse retornaListaComptcDocsPartic(CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsPartic", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaComptcDocsAdmRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse retornaListaComptcDocsAdm(CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaComptcDocsAdm", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadCadastroRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse solicAutorizDownloadCadastro(CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqComptcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse solicAutorizDownloadArqComptc(CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqComptc", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqEntregaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse solicAutorizDownloadArqEntrega(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntrega", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqEntregaPorDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse solicAutorizDownloadArqEntregaPorData(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqEntregaPorData", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest request);
        
        // CODEGEN: Generating message contract since message solicAutorizDownloadArqAnualRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse solicAutorizDownloadArqAnual(CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/solicAutorizDownloadArqAnual", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest request);
        
        // CODEGEN: Generating message contract since message retornaDtLmtEntrDocsArqsDispRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse retornaDtLmtEntrDocsArqsDisp(CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaDtLmtEntrDocsArqsDisp", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest request);
        
        // CODEGEN: Generating message contract since message retornaListaDownloadDocsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse retornaListaDownloadDocs(CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/retornaListaDownloadDocs", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest request);
        
        // CODEGEN: Generating message contract since message LoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CVMDownload.CVMWebCotas.LoginResponse Login(CVMDownload.CVMWebCotas.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cvm.gov.br/webservices/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.LoginResponse> LoginAsync(CVMDownload.CVMWebCotas.LoginRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
    public partial class sessaoIdHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string guidField;
        
        private int idSessaoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdSessao {
            get {
                return this.idSessaoField;
            }
            set {
                this.idSessaoField = value;
                this.RaisePropertyChanged("IdSessao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        public retornaListaComptcDocsRequest() {
        }
        
        public retornaListaComptcDocsRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsResult;
        
        public retornaListaComptcDocsResponse() {
        }
        
        public retornaListaComptcDocsResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsResult = retornaListaComptcDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsPartic", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsParticRequest() {
        }
        
        public retornaListaComptcDocsParticRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsParticResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsParticResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsParticResult;
        
        public retornaListaComptcDocsParticResponse() {
        }
        
        public retornaListaComptcDocsParticResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsParticResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsParticResult = retornaListaComptcDocsParticResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdm", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtIniEntregDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strNrPfPj;
        
        public retornaListaComptcDocsAdmRequest() {
        }
        
        public retornaListaComptcDocsAdmRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIniEntregDoc = strDtIniEntregDoc;
            this.strNrPfPj = strNrPfPj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaComptcDocsAdmResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaComptcDocsAdmResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaComptcDocsAdmResult;
        
        public retornaListaComptcDocsAdmResponse() {
        }
        
        public retornaListaComptcDocsAdmResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string[] retornaListaComptcDocsAdmResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaComptcDocsAdmResult = retornaListaComptcDocsAdmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastro", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string strDtRefer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadCadastroRequest() {
        }
        
        public solicAutorizDownloadCadastroRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.strDtRefer = strDtRefer;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadCadastroResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadCadastroResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadCadastroResult;
        
        public solicAutorizDownloadCadastroResponse() {
        }
        
        public solicAutorizDownloadCadastroResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadCadastroResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadCadastroResult = solicAutorizDownloadCadastroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptc", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtComptcDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqComptcRequest() {
        }
        
        public solicAutorizDownloadArqComptcRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtComptcDoc = strDtComptcDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqComptcResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqComptcResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqComptcResult;
        
        public solicAutorizDownloadArqComptcResponse() {
        }
        
        public solicAutorizDownloadArqComptcResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqComptcResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqComptcResult = solicAutorizDownloadArqComptcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntrega", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaRequest() {
        }
        
        public solicAutorizDownloadArqEntregaRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaResult;
        
        public solicAutorizDownloadArqEntregaResponse() {
        }
        
        public solicAutorizDownloadArqEntregaResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaResult = solicAutorizDownloadArqEntregaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorData", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strDtEntregaDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqEntregaPorDataRequest() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtEntregaDoc = strDtEntregaDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqEntregaPorDataResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqEntregaPorDataResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqEntregaPorDataResult;
        
        public solicAutorizDownloadArqEntregaPorDataResponse() {
        }
        
        public solicAutorizDownloadArqEntregaPorDataResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqEntregaPorDataResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqEntregaPorDataResult = solicAutorizDownloadArqEntregaPorDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnual", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strMotivoAutorizDownload;
        
        public solicAutorizDownloadArqAnualRequest() {
        }
        
        public solicAutorizDownloadArqAnualRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
            this.strMotivoAutorizDownload = strMotivoAutorizDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="solicAutorizDownloadArqAnualResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class solicAutorizDownloadArqAnualResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string solicAutorizDownloadArqAnualResult;
        
        public solicAutorizDownloadArqAnualResponse() {
        }
        
        public solicAutorizDownloadArqAnualResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string solicAutorizDownloadArqAnualResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.solicAutorizDownloadArqAnualResult = solicAutorizDownloadArqAnualResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDisp", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpDoc;
        
        public retornaDtLmtEntrDocsArqsDispRequest() {
        }
        
        public retornaDtLmtEntrDocsArqsDispRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpDoc = iCdTpDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaDtLmtEntrDocsArqsDispResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaDtLmtEntrDocsArqsDispResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string retornaDtLmtEntrDocsArqsDispResult;
        
        public retornaDtLmtEntrDocsArqsDispResponse() {
        }
        
        public retornaDtLmtEntrDocsArqsDispResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string retornaDtLmtEntrDocsArqsDispResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaDtLmtEntrDocsArqsDispResult = retornaDtLmtEntrDocsArqsDispResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocs", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iCdTpPartic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strNrPfPj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=2)]
        public int iCdTpDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=3)]
        public string strDtIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=4)]
        public string strDtFim;
        
        public retornaListaDownloadDocsRequest() {
        }
        
        public retornaListaDownloadDocsRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iCdTpPartic = iCdTpPartic;
            this.strNrPfPj = strNrPfPj;
            this.iCdTpDoc = iCdTpDoc;
            this.strDtIni = strDtIni;
            this.strDtFim = strDtFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaDownloadDocsResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class retornaListaDownloadDocsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public string[] retornaListaDownloadDocsResult;
        
        public retornaListaDownloadDocsResponse() {
        }
        
        public retornaListaDownloadDocsResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string[] retornaListaDownloadDocsResult) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.retornaListaDownloadDocsResult = retornaListaDownloadDocsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=0)]
        public int iNrSist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cvm.gov.br/webservices/", Order=1)]
        public string strSenha;
        
        public LoginRequest() {
        }
        
        public LoginRequest(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            this.sessaoIdHeader = sessaoIdHeader;
            this.iNrSist = iNrSist;
            this.strSenha = strSenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://www.cvm.gov.br/webservices/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cvm.gov.br/webservices/")]
        public CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader;
        
        public LoginResponse() {
        }
        
        public LoginResponse(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader) {
            this.sessaoIdHeader = sessaoIdHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsDownloadInfsSoapChannel : CVMDownload.CVMWebCotas.WsDownloadInfsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsDownloadInfsSoapClient : System.ServiceModel.ClientBase<CVMDownload.CVMWebCotas.WsDownloadInfsSoap>, CVMDownload.CVMWebCotas.WsDownloadInfsSoap {
        
        public WsDownloadInfsSoapClient() {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDownloadInfsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocs(CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocs(request);
        }
        
        public string[] retornaListaComptcDocs(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocsAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest request) {
            return base.Channel.retornaListaComptcDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsResponse> retornaListaComptcDocsAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocsPartic(CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsPartic(request);
        }
        
        public string[] retornaListaComptcDocsPartic(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocsPartic(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsParticResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocsParticAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest request) {
            return base.Channel.retornaListaComptcDocsParticAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsParticResponse> retornaListaComptcDocsParticAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsParticRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocsParticAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocsAdm(CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdm(request);
        }
        
        public string[] retornaListaComptcDocsAdm(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdm(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaComptcDocsAdmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaComptcDocsAdmAsync(CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest request) {
            return base.Channel.retornaListaComptcDocsAdmAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmResponse> retornaListaComptcDocsAdmAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtIniEntregDoc, string strNrPfPj) {
            CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest inValue = new CVMDownload.CVMWebCotas.retornaListaComptcDocsAdmRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIniEntregDoc = strDtIniEntregDoc;
            inValue.strNrPfPj = strNrPfPj;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaComptcDocsAdmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadCadastro(CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastro(request);
        }
        
        public string solicAutorizDownloadCadastro(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastro(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadCadastroAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest request) {
            return base.Channel.solicAutorizDownloadCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroResponse> solicAutorizDownloadCadastroAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, string strDtRefer, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadCadastroRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.strDtRefer = strDtRefer;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqComptc(CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptc(request);
        }
        
        public string solicAutorizDownloadArqComptc(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptc(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqComptcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqComptcAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest request) {
            return base.Channel.solicAutorizDownloadArqComptcAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcResponse> solicAutorizDownloadArqComptcAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtComptcDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqComptcRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtComptcDoc = strDtComptcDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqComptcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqEntrega(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntrega(request);
        }
        
        public string solicAutorizDownloadArqEntrega(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntrega(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaResponse> solicAutorizDownloadArqEntregaAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorData(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorData(request);
        }
        
        public string solicAutorizDownloadArqEntregaPorData(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorData(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqEntregaPorDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqEntregaPorDataAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest request) {
            return base.Channel.solicAutorizDownloadArqEntregaPorDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataResponse> solicAutorizDownloadArqEntregaPorDataAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strDtEntregaDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqEntregaPorDataRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtEntregaDoc = strDtEntregaDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqEntregaPorDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqAnual(CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnual(request);
        }
        
        public string solicAutorizDownloadArqAnual(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnual(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.solicAutorizDownloadArqAnualResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.solicAutorizDownloadArqAnualAsync(CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest request) {
            return base.Channel.solicAutorizDownloadArqAnualAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualResponse> solicAutorizDownloadArqAnualAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc, string strMotivoAutorizDownload) {
            CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest inValue = new CVMDownload.CVMWebCotas.solicAutorizDownloadArqAnualRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strMotivoAutorizDownload = strMotivoAutorizDownload;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).solicAutorizDownloadArqAnualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDisp(CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDisp(request);
        }
        
        public string retornaDtLmtEntrDocsArqsDisp(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest inValue = new CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDisp(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaDtLmtEntrDocsArqsDispResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaDtLmtEntrDocsArqsDispAsync(CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest request) {
            return base.Channel.retornaDtLmtEntrDocsArqsDispAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispResponse> retornaDtLmtEntrDocsArqsDispAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpDoc) {
            CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest inValue = new CVMDownload.CVMWebCotas.retornaDtLmtEntrDocsArqsDispRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpDoc = iCdTpDoc;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaDtLmtEntrDocsArqsDispAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaDownloadDocs(CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocs(request);
        }
        
        public string[] retornaListaDownloadDocs(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest inValue = new CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaDownloadDocs(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
            return retVal.retornaListaDownloadDocsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.retornaListaDownloadDocsAsync(CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest request) {
            return base.Channel.retornaListaDownloadDocsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.retornaListaDownloadDocsResponse> retornaListaDownloadDocsAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iCdTpPartic, string strNrPfPj, int iCdTpDoc, string strDtIni, string strDtFim) {
            CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest inValue = new CVMDownload.CVMWebCotas.retornaListaDownloadDocsRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iCdTpPartic = iCdTpPartic;
            inValue.strNrPfPj = strNrPfPj;
            inValue.iCdTpDoc = iCdTpDoc;
            inValue.strDtIni = strDtIni;
            inValue.strDtFim = strDtFim;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).retornaListaDownloadDocsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVMDownload.CVMWebCotas.LoginResponse CVMDownload.CVMWebCotas.WsDownloadInfsSoap.Login(CVMDownload.CVMWebCotas.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public void Login(ref CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            CVMDownload.CVMWebCotas.LoginRequest inValue = new CVMDownload.CVMWebCotas.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            CVMDownload.CVMWebCotas.LoginResponse retVal = ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).Login(inValue);
            sessaoIdHeader = retVal.sessaoIdHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.LoginResponse> CVMDownload.CVMWebCotas.WsDownloadInfsSoap.LoginAsync(CVMDownload.CVMWebCotas.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CVMDownload.CVMWebCotas.LoginResponse> LoginAsync(CVMDownload.CVMWebCotas.sessaoIdHeader sessaoIdHeader, int iNrSist, string strSenha) {
            CVMDownload.CVMWebCotas.LoginRequest inValue = new CVMDownload.CVMWebCotas.LoginRequest();
            inValue.sessaoIdHeader = sessaoIdHeader;
            inValue.iNrSist = iNrSist;
            inValue.strSenha = strSenha;
            return ((CVMDownload.CVMWebCotas.WsDownloadInfsSoap)(this)).LoginAsync(inValue);
        }
    }
}
