// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package financialdatagrabber.services.cvm

case class RetornaListaComptcDocs(iCdTpDoc: Int,
  strDtIniEntregDoc: Option[String] = None)
      


case class RetornaListaComptcDocsResponse(retornaListaComptcDocsResult: Option[financialdatagrabber.services.cvm.ArrayOfString] = None)
      


case class ArrayOfString(string: Option[String]*)
      


case class SessaoIdHeader(Guid: Option[String] = None,
  IdSessao: Int,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map())
      


case class RetornaListaComptcDocsPartic(iCdTpDoc: Int,
  strDtIniEntregDoc: Option[String] = None,
  strNrPfPj: Option[String] = None)
      


case class RetornaListaComptcDocsParticResponse(retornaListaComptcDocsParticResult: Option[financialdatagrabber.services.cvm.ArrayOfString] = None)
      


case class RetornaListaComptcDocsAdm(iCdTpDoc: Int,
  strDtIniEntregDoc: Option[String] = None,
  strNrPfPj: Option[String] = None)
      


case class RetornaListaComptcDocsAdmResponse(retornaListaComptcDocsAdmResult: Option[financialdatagrabber.services.cvm.ArrayOfString] = None)
      


case class SolicAutorizDownloadCadastro(strDtRefer: Option[String] = None,
  strMotivoAutorizDownload: Option[String] = None)
      


case class SolicAutorizDownloadCadastroResponse(solicAutorizDownloadCadastroResult: Option[String] = None)
      


case class SolicAutorizDownloadArqComptc(iCdTpDoc: Int,
  strDtComptcDoc: Option[String] = None,
  strMotivoAutorizDownload: Option[String] = None)
      


case class SolicAutorizDownloadArqComptcResponse(solicAutorizDownloadArqComptcResult: Option[String] = None)
      


case class SolicAutorizDownloadArqEntrega(iCdTpDoc: Int,
  strMotivoAutorizDownload: Option[String] = None)
      


case class SolicAutorizDownloadArqEntregaResponse(solicAutorizDownloadArqEntregaResult: Option[String] = None)
      


case class SolicAutorizDownloadArqEntregaPorData(iCdTpDoc: Int,
  strDtEntregaDoc: Option[String] = None,
  strMotivoAutorizDownload: Option[String] = None)
      


case class SolicAutorizDownloadArqEntregaPorDataResponse(solicAutorizDownloadArqEntregaPorDataResult: Option[String] = None)
      


case class SolicAutorizDownloadArqAnual(iCdTpDoc: Int,
  strMotivoAutorizDownload: Option[String] = None)
      


case class SolicAutorizDownloadArqAnualResponse(solicAutorizDownloadArqAnualResult: Option[String] = None)
      


case class RetornaDtLmtEntrDocsArqsDisp(iCdTpDoc: Int)
      


case class RetornaDtLmtEntrDocsArqsDispResponse(retornaDtLmtEntrDocsArqsDispResult: Option[String] = None)
      


case class RetornaListaDownloadDocs(iCdTpPartic: Int,
  strNrPfPj: Option[String] = None,
  iCdTpDoc: Int,
  strDtIni: Option[String] = None,
  strDtFim: Option[String] = None)
      


case class RetornaListaDownloadDocsResponse(retornaListaDownloadDocsResult: Option[financialdatagrabber.services.cvm.ArrayOfString] = None)
      


case class Login(iNrSist: Int,
  strSenha: Option[String] = None)
      


case class LoginResponse()
      

